version: '3.0'
services:

  queue:
    #build:
    container_name: mq
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
      - '9001:9001'
    #enviroment:
    volumes:
     - ./mq/mosquitto.conf:/mosquitto/config/mosquitto.conf
  database:
    #build: 
    container_name: db
    image: mongo:5.0.22
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  generator:
    build: ./generator/generator
    stdin_open: true
    volumes:
      - ./generator/appsettings.json:/App/appsettings.json
    #image:



  # frontend:
  #   build:
  #   #image:
  #   ports:
  #   enviroment:
  #   networks:
  #     - networkName

  # backend:
  #   build:
  #   #image:
  #   ports:
  #   enviroment:


#
#networks:

